package by.ktp;

import by.ktp.connectors.Connector;

import java.util.ArrayList;
import java.util.List;

public class BrainStructure {
    public Brain generateNewBrain() {
        //todo need to be generated by Machine Learning module
        Brain tempTestBrain = new Brain();
        List<Connector> eyeBrainCell1Connectors = new ArrayList<>();
        Connector eyeBeanAfferentConnector = new Connector(1, 1, 1_000_000_000, 0, 0);
        eyeBrainCell1Connectors.add(eyeBeanAfferentConnector);
        tempTestBrain.addAfferentBrainCell(eyeBrainCell1Connectors);
        return null;
    }
}
